// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: rso-comms/lobby_svc.proto

package ___

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndGameReason int32

const (
	EndGameReason_WIN        EndGameReason = 0
	EndGameReason_INACTIVITY EndGameReason = 1
)

// Enum value maps for EndGameReason.
var (
	EndGameReason_name = map[int32]string{
		0: "WIN",
		1: "INACTIVITY",
	}
	EndGameReason_value = map[string]int32{
		"WIN":        0,
		"INACTIVITY": 1,
	}
)

func (x EndGameReason) Enum() *EndGameReason {
	p := new(EndGameReason)
	*p = x
	return p
}

func (x EndGameReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndGameReason) Descriptor() protoreflect.EnumDescriptor {
	return file_rso_comms_lobby_svc_proto_enumTypes[0].Descriptor()
}

func (EndGameReason) Type() protoreflect.EnumType {
	return &file_rso_comms_lobby_svc_proto_enumTypes[0]
}

func (x EndGameReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndGameReason.Descriptor instead.
func (EndGameReason) EnumDescriptor() ([]byte, []int) {
	return file_rso_comms_lobby_svc_proto_rawDescGZIP(), []int{0}
}

type GameID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GameID) Reset() {
	*x = GameID{}
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameID) ProtoMessage() {}

func (x *GameID) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameID.ProtoReflect.Descriptor instead.
func (*GameID) Descriptor() ([]byte, []int) {
	return file_rso_comms_lobby_svc_proto_rawDescGZIP(), []int{0}
}

func (x *GameID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string  `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Size     float32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_rso_comms_lobby_svc_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LiveDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *GameID   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players []*Player `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *LiveDataRequest) Reset() {
	*x = LiveDataRequest{}
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiveDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiveDataRequest) ProtoMessage() {}

func (x *LiveDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiveDataRequest.ProtoReflect.Descriptor instead.
func (*LiveDataRequest) Descriptor() ([]byte, []int) {
	return file_rso_comms_lobby_svc_proto_rawDescGZIP(), []int{2}
}

func (x *LiveDataRequest) GetId() *GameID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *LiveDataRequest) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type EndGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *GameID       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reason EndGameReason `protobuf:"varint,2,opt,name=reason,proto3,enum=rso_comms.EndGameReason" json:"reason,omitempty"`
}

func (x *EndGameRequest) Reset() {
	*x = EndGameRequest{}
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndGameRequest) ProtoMessage() {}

func (x *EndGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_lobby_svc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndGameRequest.ProtoReflect.Descriptor instead.
func (*EndGameRequest) Descriptor() ([]byte, []int) {
	return file_rso_comms_lobby_svc_proto_rawDescGZIP(), []int{3}
}

func (x *EndGameRequest) GetId() *GameID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *EndGameRequest) GetReason() EndGameReason {
	if x != nil {
		return x.Reason
	}
	return EndGameReason_WIN
}

var File_rso_comms_lobby_svc_proto protoreflect.FileDescriptor

var file_rso_comms_lobby_svc_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x73, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2f, 0x6c, 0x6f, 0x62, 0x62,
	0x79, 0x5f, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x73, 0x6f,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x22, 0x18, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x38, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x61, 0x0a, 0x0f, 0x4c, 0x69,
	0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x73, 0x6f, 0x5f,
	0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x2b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x65, 0x0a,
	0x0e, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x73,
	0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x72, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x45,
	0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x2a, 0x28, 0x0a, 0x0d, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0e,
	0x0a, 0x0a, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x49, 0x54, 0x59, 0x10, 0x01, 0x32, 0x8f,
	0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x2e,
	0x72, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x72, 0x73, 0x6f, 0x5f, 0x63,
	0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x1a, 0x2e, 0x72, 0x73, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x4c, 0x69, 0x76, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x72, 0x73,
	0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x00,
	0x42, 0x05, 0x5a, 0x03, 0x2e, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rso_comms_lobby_svc_proto_rawDescOnce sync.Once
	file_rso_comms_lobby_svc_proto_rawDescData = file_rso_comms_lobby_svc_proto_rawDesc
)

func file_rso_comms_lobby_svc_proto_rawDescGZIP() []byte {
	file_rso_comms_lobby_svc_proto_rawDescOnce.Do(func() {
		file_rso_comms_lobby_svc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rso_comms_lobby_svc_proto_rawDescData)
	})
	return file_rso_comms_lobby_svc_proto_rawDescData
}

var file_rso_comms_lobby_svc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rso_comms_lobby_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rso_comms_lobby_svc_proto_goTypes = []any{
	(EndGameReason)(0),      // 0: rso_comms.EndGameReason
	(*GameID)(nil),          // 1: rso_comms.GameID
	(*Player)(nil),          // 2: rso_comms.Player
	(*LiveDataRequest)(nil), // 3: rso_comms.LiveDataRequest
	(*EndGameRequest)(nil),  // 4: rso_comms.EndGameRequest
}
var file_rso_comms_lobby_svc_proto_depIdxs = []int32{
	1, // 0: rso_comms.LiveDataRequest.id:type_name -> rso_comms.GameID
	2, // 1: rso_comms.LiveDataRequest.players:type_name -> rso_comms.Player
	1, // 2: rso_comms.EndGameRequest.id:type_name -> rso_comms.GameID
	0, // 3: rso_comms.EndGameRequest.reason:type_name -> rso_comms.EndGameReason
	4, // 4: rso_comms.LobbyService.DeleteGame:input_type -> rso_comms.EndGameRequest
	3, // 5: rso_comms.LobbyService.UpdateLiveData:input_type -> rso_comms.LiveDataRequest
	1, // 6: rso_comms.LobbyService.DeleteGame:output_type -> rso_comms.GameID
	1, // 7: rso_comms.LobbyService.UpdateLiveData:output_type -> rso_comms.GameID
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rso_comms_lobby_svc_proto_init() }
func file_rso_comms_lobby_svc_proto_init() {
	if File_rso_comms_lobby_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rso_comms_lobby_svc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rso_comms_lobby_svc_proto_goTypes,
		DependencyIndexes: file_rso_comms_lobby_svc_proto_depIdxs,
		EnumInfos:         file_rso_comms_lobby_svc_proto_enumTypes,
		MessageInfos:      file_rso_comms_lobby_svc_proto_msgTypes,
	}.Build()
	File_rso_comms_lobby_svc_proto = out.File
	file_rso_comms_lobby_svc_proto_rawDesc = nil
	file_rso_comms_lobby_svc_proto_goTypes = nil
	file_rso_comms_lobby_svc_proto_depIdxs = nil
}
