// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.19.6
// source: rso-comms/game.proto

package ___

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rso_comms_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{0}
}

type GameID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GameID) Reset() {
	*x = GameID{}
	mi := &file_rso_comms_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameID) ProtoMessage() {}

func (x *GameID) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameID.ProtoReflect.Descriptor instead.
func (*GameID) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GameLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string  `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Id       *GameID `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GameLocation) Reset() {
	*x = GameLocation{}
	mi := &file_rso_comms_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameLocation) ProtoMessage() {}

func (x *GameLocation) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameLocation.ProtoReflect.Descriptor instead.
func (*GameLocation) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{2}
}

func (x *GameLocation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GameLocation) GetId() *GameID {
	if x != nil {
		return x.Id
	}
	return nil
}

type GameIDList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GameIDList) Reset() {
	*x = GameIDList{}
	mi := &file_rso_comms_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameIDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameIDList) ProtoMessage() {}

func (x *GameIDList) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameIDList.ProtoReflect.Descriptor instead.
func (*GameIDList) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{3}
}

func (x *GameIDList) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GameData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *GameData) Reset() {
	*x = GameData{}
	mi := &file_rso_comms_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameData) ProtoMessage() {}

func (x *GameData) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameData.ProtoReflect.Descriptor instead.
func (*GameData) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameData) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string  `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Size     float32 `protobuf:"fixed32,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_rso_comms_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_rso_comms_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_rso_comms_game_proto_rawDescGZIP(), []int{5}
}

func (x *Player) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Player) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_rso_comms_game_proto protoreflect.FileDescriptor

var file_rso_comms_game_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x73, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x73, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x18, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0c, 0x47, 0x61, 0x6d,
	0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e,
	0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x2d,
	0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0x38, 0x0a,
	0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x32, 0x78, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x20, 0x0a,
	0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x07, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x1a, 0x07, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x00, 0x12,
	0x20, 0x0a, 0x08, 0x4c, 0x69, 0x76, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x07, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x49, 0x44, 0x1a, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x00, 0x42, 0x05, 0x5a, 0x03, 0x2e, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rso_comms_game_proto_rawDescOnce sync.Once
	file_rso_comms_game_proto_rawDescData = file_rso_comms_game_proto_rawDesc
)

func file_rso_comms_game_proto_rawDescGZIP() []byte {
	file_rso_comms_game_proto_rawDescOnce.Do(func() {
		file_rso_comms_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_rso_comms_game_proto_rawDescData)
	})
	return file_rso_comms_game_proto_rawDescData
}

var file_rso_comms_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_rso_comms_game_proto_goTypes = []any{
	(*Empty)(nil),        // 0: Empty
	(*GameID)(nil),       // 1: GameID
	(*GameLocation)(nil), // 2: GameLocation
	(*GameIDList)(nil),   // 3: GameIDList
	(*GameData)(nil),     // 4: GameData
	(*Player)(nil),       // 5: Player
}
var file_rso_comms_game_proto_depIdxs = []int32{
	1, // 0: GameLocation.id:type_name -> GameID
	5, // 1: GameData.players:type_name -> Player
	0, // 2: GameService.CreateGame:input_type -> Empty
	1, // 3: GameService.DeleteGame:input_type -> GameID
	1, // 4: GameService.LiveData:input_type -> GameID
	2, // 5: GameService.CreateGame:output_type -> GameLocation
	1, // 6: GameService.DeleteGame:output_type -> GameID
	4, // 7: GameService.LiveData:output_type -> GameData
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rso_comms_game_proto_init() }
func file_rso_comms_game_proto_init() {
	if File_rso_comms_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rso_comms_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rso_comms_game_proto_goTypes,
		DependencyIndexes: file_rso_comms_game_proto_depIdxs,
		MessageInfos:      file_rso_comms_game_proto_msgTypes,
	}.Build()
	File_rso_comms_game_proto = out.File
	file_rso_comms_game_proto_rawDesc = nil
	file_rso_comms_game_proto_goTypes = nil
	file_rso_comms_game_proto_depIdxs = nil
}
